# Generated by Django 6.0.4 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('fecha_ultima_vez', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_guardadas', to='tienda.cliente')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.municipio')),
            ],
            options={
                'ordering': ['-fecha_ultima_vez'],
                'unique_together': {('cliente', 'municipio', 'direccion')},
            },
        ),
    ]
