# Generated by Django 6.0.4 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_ubicacioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='talla',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='talla',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
